# Generated by Django 5.2.14 on 2026-05-14 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airport',
            old_name='name',
            new_name='city',
        ),
    ]
